### PR TITLE
Fix modcc precedence parsing bug

### LINKED ISSUE #94: Bug: modcc: incorrect parsing of negative terms in arithmetic expression
The expression "2 * 7 - 3 * 11 + 4 * 13" incorrectly parses as:
```
((2 * 7) - ((3 * 11) + (4 * 13)))
```
The correct parse should be:
```
(((2 * 7) - (3 * 11)) + (4 * 13))
```

### PR DESCRIPTION
**Pull request by halfflat**
* Modify `parse_expression` to take a controlling (parent) precedence.
* `parse_expression` folds left over sequences of sub-expressions with decreasing operator precedence (accumulates in `lhs`).
* Use recursion rather than accumulator for left fold in `parse_binop` to simplify code logic.
* Extend parser unit test to cover more complicated, multi-level expression.
* Remove (now) redundant parenthesis from derivative check block in kinetic rewriter test.

Fixes #94

### CODE REVIEW

File: modcc/parser.cpp [hunk 1]
```diff
@@ -1215,44 +1222,35 @@ expression_ptr Parser::parse_integer() {
 }
 
 expression_ptr Parser::parse_binop(expression_ptr&& lhs, Token op_left) {
```
Comment (bcumming) [inline modcc/parser.cpp]: The `Token`type isn't trivially copyable because `std::string`. It is being passed by value here: would passing by const reference also work From a cursory glance at the code, it looks like it would.
