### PR TITLE
Bug fix for issue #196

### LINKED ISSUE #196: modcc segfaults when compiled with -ffast-math
Reproduced with gcc 5.3 and gcc 6.3 doing:

`modcc -t cpu mechanisms/mod/expsyn.mod`

Configuration:

```
 CMAKE_BUILD_TYPE                 Debug                                                                            
 CMAKE_INSTALL_PREFIX             /usr/local                                                                       
 MODCC_BIN                        MODCC_BIN-NOTFOUND                                                               
 NMC_AUTO_RUN_MODCC_ON_CHANGES    ON                                                                               
 NMC_BUILD_VALIDATION_DATA        OFF                                                                              
 NMC_DISTRIBUTED_MODEL            serial                                                                           
 NMC_SYSTEM_TYPE                  Generic                                                                          
 NMC_THREADING_MODEL              tbb                                                                              
 NMC_USE_OPTIMIZED_KERNELS        OFF                                                                              
 NMC_VALIDATION_DATA_DIR          /users/karakasv/Devel/nestmc-proto/validation/data                               
 NMC_VECTORIZE_TARGET             none                                                                             
 NMC_WITH_ASSERTIONS              ON                                                                               
 NMC_WITH_CUDA                    OFF                                                                              
 NMC_WITH_PROFILING               ON                                                                               
 NMC_WITH_TRACE                   OFF                                                                              
 unwind_library_generic           unwind_library_generic-NOTFOUND                                                  
 unwind_library_target            unwind_library_target-NOTFOUND                                                   
 CMAKE_CXX_FLAGS                  -ffast-math                                                   
```

Stack trace:
```
(gdb) bt
#0  0x00000000005325d9 in make_unique_local_assign (scope=..., e=0x0, prefix=...)
    at /users/karakasv/Devel/nestmc-proto/modcc/astmanip.cpp:16
#1  0x000000000051779d in CnexpSolverVisitor::visit (this=0x5acf80, e=0x5ab4d0)
    at /users/karakasv/Devel/nestmc-proto/modcc/solvers.cpp:55
#2  0x000000000053f893 in AssignmentExpression::accept (this=0x5ab4d0, v=0x5acf80)
    at /users/karakasv/Devel/nestmc-proto/modcc/expression.cpp:924
#3  0x00000000004f37a8 in BlockRewriterBase::visit (this=0x5acf80, e=0x5ab560)
    at /users/karakasv/Devel/nestmc-proto/modcc/visitor.hpp:114
#4  0x00000000005174ff in CnexpSolverVisitor::visit (this=0x5acf80, e=0x5ab560)
    at /users/karakasv/Devel/nestmc-proto/modcc/solvers.cpp:27
#5  0x000000000053f35f in BlockExpression::accept (this=0x5ab560, v=0x5acf80)
    at /users/karakasv/Devel/nestmc-proto/modcc/expression.cpp:849
#6  0x00000000004efcf8 in Module::semantic (this=0x7fffffffb990)
    at /users/karakasv/Devel/nestmc-proto/modcc/module.cpp:447
#7  0x00000000004ba223 in main (argc=5, argv=0x7fffffffd128)
    at /users/karakasv/Devel/nestmc-proto/modcc/modcc.cpp:108
```

The problem starts from symdiff.cpp, where [this](https://github.com/eth-cscs/nestmc-proto/blob/master/modcc/symdiff.cpp#L660) check does not succeed and does not populate the `result.coef[id]`. It then comes up in solvers.cpp [here](https://github.com/eth-cscs/nestmc-proto/blob/master/modcc/solvers.cpp#L51), where `r.coef[s]` will insert a new `expression_ptr` that wraps  basically `nullptr`, since `s` does not exist, which finally leads to the segfault two lines later.

I cannot figure out an obvious fix, since a "field" knowledge is needed.

### PR DESCRIPTION
**Pull request by halfflat**
Fixes #196.

Correct treatment of missing coefficients in `cnexp` solver; implement workaround for compilation with `-ffast-math`.

* Extend `EXPECT_EXPR_EQ` functionality with wrapper that works with `Expression *` and `expression_ptr` arguments.
* Replace string comparison checks in `test_symdiff.cpp` with equivalents that use `EXPECT_EXPR_EQ`.
* Check explicitly for missing coefficient in `cnexp` solver, which should be treated equivalently to zero.
* When bulding with `-ffast-math` complain with a `#warning` and use a different dummy value in the constant simplification code.

### CODE REVIEW

File: modcc/symdiff.cpp [hunk 1]
```diff
@@ -266,7 +267,13 @@ class SymPDiffVisitor: public Visitor, public error_stack {
 // from the given one with constant simplifications.
 
 long double expr_value(Expression* e) {
-    return e && e->is_number()? e->is_number()->value(): NAN;
+#ifdef __FAST_MATH__
```
Comment (bcumming) [inline modcc/symdiff.cpp]: I think we should just avoid fast math, or worst case it is something that should be turned on in files where desired.

Comment (bcumming) [inline modcc/symdiff.cpp]: I understand that the reason for this patch is to get something working for the KNL workshop.

For the workshop can you cross compile with modcc compiled without the fast-math flags.

**Comment by bcumming** [comment]
@halfflat, how about removing the `ffast-math` work around, and just submitting with the bug fixes?

**Comment by halfflat** [comment]
Happy to remove the `-ffast-math` work around.
